site_name: "Generalized Nash Kit"

theme:
  name: material
  # palette:
  #   primary: blue grey
  palette:
  - scheme: default
    primary: slate
    accent: teal
  
  font:
    text: IBM Plex Sans
    code: JetBrains Mono
   
  # features:
  #   - navigation.tabs
  #   - navigation.sections
  #   - navigation.indexes

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - toc.follow

extra_css:
- stylesheets/extra.css


plugins:
  - awesome-pages
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_toc_entry: false
            show_signature_annotations: true
            separate_signature: true
            show_category_heading: false   # adds "Classes", "Functions", "Methods"
            show_submodules: false
            show_bases: false
            show_source: false
            show_source_order: true
            members_order: source


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - toc
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path: .
  
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6


  

# Global site menu
# https://www.mkdocs.org/user-guide/writing-your-docs/#file-layout
nav:
  - Home: 
    - Overview: index.md
    - GNE Problems: 
        - Model: gne_problems.md
        - Theory: gne_theory.md
    - D-GBNE Problems: 
        - Model: dgbne_problems.md
        - Theory: dgbne_theory.md

  - Getting Started: 
    - Installation: getting_started/installation.md
    - Quickstart: getting_started/quick_start.md

  - Guides:
    - Core Concepts: guides/core_concepts.md
    - Create New GNE Problems: guides/gne_problems.md
    - Create New D-GBNE Problems: guides/dgbne_problems.md
    - Creating an Algorithm: guides/creating_algorithm.md
  
  - API Reference:
      - Overview: reference/index.md
      - Problems:
          - BaseProblem: reference/problems/base_problem.md
          - BayesianProblem: reference/problems/bayesian_problem.md
      - Players:
          - BasePlayer: reference/players/base_player.md
          - BayesianPlayer: reference/players/bayesian_player.md
      - Algorithms:
          - BaseAlgorithm: reference/algorithms/base_algorithm.md
          - EnergyMethod: reference/algorithms/energy_method.md
      - Utilities:
          - construct_vectors: reference/functions/construct_vectors.md
          - create_wrapped_function: reference/functions/create_wrapped_function.md
          - flatten_variables: reference/functions/flatten_variables.md
          - one_hot_encoding: reference/functions/one_hot_encoding.md
      - Types:
          - Object Types: reference/types/object_types.md
          - Function Types: reference/types/type_functions.md

  - Examples: 
    - Overview: examples/index.md
    - GNE Examples:
        - Problem A1: examples/gne/A1.md
        - Problem A2: examples/gne/A2.md
        - Problem A3: examples/gne/A3.md
        - Problem A4: examples/gne/A4.md
        - Problem A5: examples/gne/A5.md
        - Problem A6: examples/gne/A6.md
        - Problem A7: examples/gne/A7.md
        - Problem A8: examples/gne/A8.md
        - Problem A9a: examples/gne/A9a.md
        - Problem A9b: examples/gne/A9b.md
        - Problem A10a: examples/gne/A10a.md
        - Problem A11: examples/gne/A11.md
        - Problem A12: examples/gne/A12.md
        - Problem A13: examples/gne/A13.md
        - Problem A14: examples/gne/A14.md
        - Problem A15: examples/gne/A15.md
        - Problem A16: examples/gne/A16.md
        - Problem A17: examples/gne/A17.md
        - Problem A18: examples/gne/A18.md
    - D-GBNE Examples:
        - Quadratic Game: examples/bayesian/quadratic.md
        - Wireless Bandwidth Allocation: examples/bayesian/allocation.md
        - Multistatic Radar Power Allocation: examples/bayesian/radar.md

  - Development:
      - Overview: development/overview.md
      - Standards: development/standards.md